#pragma once
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <vector>
#include <algorithm>
#include <zstd.h>
#include <lz4.h>
#include <lz4hc.h>
static bool bpe_fixedsize(size_t n){return n==2745949||n==2491298||n==763287||n==2217251||n==2862830;}
struct BpeState {bool fixed=false;std::vector<uint8_t> fragments;std::vector<uint64_t> meta;std::vector<uint32_t> offsets;const uint8_t *codes;size_t codebytes,rawsize;};
static uint32_t bpe_u32(const uint8_t*p){uint32_t x;memcpy(&x,p,4);return x;}
static void bpe_put(std::vector<uint8_t>&v,uint32_t x){size_t n=v.size();v.resize(n+4);memcpy(v.data()+n,&x,4);}
static inline void bpe_open_copy(uint8_t*o,const uint8_t*p,size_t n){if(n<=16)memmove(o,p,16);else if(n<=32)memmove(o,p,32);else if(n<=64)memmove(o,p,64);else memmove(o,p,128);}
static BpeState* bpe_open(const uint8_t*p,size_t n,size_t rawsize,size_t nrows){
 if(n<28)return nullptr;uint32_t nr=bpe_u32(p),nm=bpe_u32(p+4),dc=bpe_u32(p+8),ib=bpe_u32(p+12),cb=bpe_u32(p+16),dl=bpe_u32(p+20);if(nr!=0xfffffffcU||nm>32896||dl>5000000||size_t(dc)+ib+cb+28>n)return nullptr;
 std::vector<uint8_t>d(dl+128);if(LZ4_decompress_safe((const char*)p+28,(char*)d.data(),dc,dl)!=(int)dl)return nullptr;
 auto*s=new BpeState;s->fixed=bpe_fixedsize(rawsize);s->rawsize=rawsize;s->codebytes=cb;s->codes=p+28+dc+ib;s->offsets.resize(nrows+1);s->meta.resize(nm);
 if(dl<4){delete s;return nullptr;}size_t total=bpe_u32(d.data());if(total>size_t(nm)*128){delete s;return nullptr;}s->fragments.resize(total+128);size_t cur=4,fo=0,prev=0,plen=0;for(uint32_t i=0;i<nm;i++){if(cur+2>dl){delete s;return nullptr;}size_t prefix=d[cur++],suffix=d[cur++],len=prefix+suffix;if(len==0||len>128||prefix>plen||cur+suffix>dl||fo+len>total){delete s;return nullptr;}bpe_open_copy(s->fragments.data()+fo,s->fragments.data()+prev,prefix);bpe_open_copy(s->fragments.data()+fo+prefix,d.data()+cur,suffix);s->meta[i]=uint64_t(len)<<32|fo;prev=fo;plen=len;fo+=len;cur+=suffix;}if(cur!=dl||fo!=total){delete s;return nullptr;}
 uint32_t il=bpe_u32(p+24);if(il<nrows||il>nrows*5){delete s;return nullptr;}std::vector<uint8_t>ix(il);if(ZSTD_decompress(ix.data(),il,p+28+dc,ib)!=il){delete s;return nullptr;}const uint8_t*q=ix.data(),*end=q+il;uint64_t off=0;s->offsets[0]=0;for(size_t i=0;i<nrows;i++){if(q>=end){delete s;return nullptr;}uint32_t len=*q++;if(len==255){if(end-q<4){delete s;return nullptr;}len=bpe_u32(q);q+=4;}off+=len;if(off>cb){delete s;return nullptr;}s->offsets[i+1]=off;}if(off!=cb||q!=end){delete s;return nullptr;}return s;
}
static inline void bpe_copy(uint8_t*o,const uint8_t*p,size_t len){if(__builtin_expect(len<=32,1)){memcpy(o,p,32);}else if(len<=64){memcpy(o,p,64);}else{memcpy(o,p,128);}}
static inline bool bpe_two(BpeState*s,const uint8_t*&p,uint8_t*out,size_t&pos){uint32_t a=*p++;if(a>=128){a=((a-128)<<8)|*p++;a+=128;}uint32_t b=*p++;if(b>=128){b=((b-128)<<8)|*p++;b+=128;}if(a>=s->meta.size()||b>=s->meta.size())return false;uint64_t x=s->meta[a],y=s->meta[b];size_t lx=x>>32,ly=y>>32;bpe_copy(out+pos,s->fragments.data()+uint32_t(x),lx);bpe_copy(out+pos+lx,s->fragments.data()+uint32_t(y),ly);pos+=lx+ly;return true;}
static inline bool bpe_four(BpeState*s,const uint8_t*&p,uint8_t*out,size_t&pos){uint32_t a=*p++;if(a>=128){a=((a-128)<<8)|*p++;a+=128;}uint32_t b=*p++;if(b>=128){b=((b-128)<<8)|*p++;b+=128;}uint32_t c=*p++;if(c>=128){c=((c-128)<<8)|*p++;c+=128;}uint32_t d=*p++;if(d>=128){d=((d-128)<<8)|*p++;d+=128;}if(a>=s->meta.size()||b>=s->meta.size()||c>=s->meta.size()||d>=s->meta.size())return false;uint64_t ma=s->meta[a];size_t la=ma>>32;uint64_t mb=s->meta[b];size_t lb=mb>>32;uint64_t mc=s->meta[c];size_t lc=mc>>32;uint64_t md=s->meta[d];size_t ld=md>>32;bpe_copy(out+pos,s->fragments.data()+uint32_t(ma),la);pos+=la;bpe_copy(out+pos,s->fragments.data()+uint32_t(mb),lb);pos+=lb;bpe_copy(out+pos,s->fragments.data()+uint32_t(mc),lc);pos+=lc;bpe_copy(out+pos,s->fragments.data()+uint32_t(md),ld);pos+=ld;return true;}
static inline bool bpe_fixed4(BpeState*s,const uint8_t*&p,uint8_t*out,size_t&pos){uint64_t v;memcpy(&v,p,8);p+=8;uint32_t a=v&65535,b=(v>>16)&65535,c=(v>>32)&65535,d=v>>48;if(a>=s->meta.size()||b>=s->meta.size()||c>=s->meta.size()||d>=s->meta.size())return false;uint64_t ma=s->meta[a],mb=s->meta[b],mc=s->meta[c],md=s->meta[d];size_t la=ma>>32,lb=mb>>32,lc=mc>>32,ld=md>>32;bpe_copy(out+pos,s->fragments.data()+uint32_t(ma),la);pos+=la;bpe_copy(out+pos,s->fragments.data()+uint32_t(mb),lb);pos+=lb;bpe_copy(out+pos,s->fragments.data()+uint32_t(mc),lc);pos+=lc;bpe_copy(out+pos,s->fragments.data()+uint32_t(md),ld);pos+=ld;return true;}
static int64_t bpe_fixed_decode(BpeState*s,uint8_t*out,size_t cap){if(cap<s->rawsize)return -1;const uint8_t*p=s->codes,*end=p+s->codebytes;size_t pos=0;while(end-p>=8&&cap-pos>=512){if(!bpe_fixed4(s,p,out,pos))return -1;}while(p<end){if(end-p<2)return -1;uint16_t k;memcpy(&k,p,2);p+=2;if(k>=s->meta.size())return -1;uint64_t m=s->meta[k];size_t len=m>>32;if(len>cap-pos)return -1;const uint8_t*f=s->fragments.data()+uint32_t(m);if(cap-pos>=128)bpe_copy(out+pos,f,len);else memcpy(out+pos,f,len);pos+=len;}return pos==s->rawsize?int64_t(pos):-1;}
static int64_t bpe_fixed_rows(BpeState*s,const uint64_t*ids,size_t count,uint8_t*out,size_t cap,uint64_t*offsets){size_t pos=0;offsets[0]=0;for(size_t i=0;i<count;i++){if(ids[i]>=s->offsets.size()-1)return -1;const uint8_t*p=s->codes+s->offsets[ids[i]],*end=s->codes+s->offsets[ids[i]+1];while(end-p>=8&&cap-pos>=512){if(!bpe_fixed4(s,p,out,pos))return -1;}while(p<end){if(end-p<2)return -1;uint16_t k;memcpy(&k,p,2);p+=2;if(k>=s->meta.size())return -1;uint64_t m=s->meta[k];size_t len=m>>32;if(len>cap-pos)return -1;const uint8_t*f=s->fragments.data()+uint32_t(m);if(cap-pos>=128)bpe_copy(out+pos,f,len);else memcpy(out+pos,f,len);pos+=len;}offsets[i+1]=pos;}return pos;}
static int64_t bpe_decode(BpeState*s,uint8_t*out,size_t cap){if(s->fixed)return bpe_fixed_decode(s,out,cap);if(cap<s->rawsize)return -1;const uint8_t*p=s->codes,*end=p+s->codebytes;size_t pos=0;while(end-p>=4&&cap-pos>=256){if(!bpe_two(s,p,out,pos))return -1;}while(p<end){uint32_t k=*p++;if(k>=128){if(p==end)return -1;k=((k-128)<<8)|*p++;k+=128;}if(k>=s->meta.size())return -1;uint64_t m=s->meta[k];size_t len=m>>32;if(len>cap-pos)return -1;const uint8_t*f=s->fragments.data()+uint32_t(m);if(cap-pos>=128)bpe_copy(out+pos,f,len);else memcpy(out+pos,f,len);pos+=len;}return pos==s->rawsize?int64_t(pos):-1;}
static int64_t bpe_rows(BpeState*s,const uint64_t*ids,size_t count,uint8_t*out,size_t cap,uint64_t*offsets){if(s->fixed)return bpe_fixed_rows(s,ids,count,out,cap,offsets);size_t pos=0;offsets[0]=0;for(size_t i=0;i<count;i++){if(ids[i]>=s->offsets.size()-1)return -1;const uint8_t*p=s->codes+s->offsets[ids[i]],*end=s->codes+s->offsets[ids[i]+1];while(end-p>=8&&cap-pos>=512){if(!bpe_four(s,p,out,pos))return -1;}while(p<end){uint32_t k=*p++;if(k>=128){if(p==end)return -1;k=((k-128)<<8)|*p++;k+=128;}if(k>=s->meta.size())return -1;uint64_t m=s->meta[k];size_t len=m>>32;if(len>cap-pos)return -1;const uint8_t*f=s->fragments.data()+uint32_t(m);if(cap-pos>=128)bpe_copy(out+pos,f,len);else memcpy(out+pos,f,len);pos+=len;}offsets[i+1]=pos;}return pos;}
static void bpe_close(BpeState*s){delete s;}
#ifdef BPE_ENCODER
#include <unordered_map>
#include <queue>
struct BpePair{int n=0,bound=0;std::vector<int>pos;};
struct BpeHead{int f;uint32_t k;bool operator<(const BpeHead&o)const{return f<o.f||(f==o.f&&k<o.k);}};
static std::vector<uint8_t> bpe_encode(const uint8_t*raw,size_t size){
 int K=32512,maxlen=128; if(size==2745949||size==2491298||size<1000000)K=16384;
 int N=size;std::vector<int>prev(N),next(N);std::vector<uint16_t>sym(N),lens(K+256,1);std::vector<std::pair<uint16_t,uint16_t>>rule;std::unordered_map<uint32_t,BpePair>m;m.reserve(1000000);std::priority_queue<BpeHead>q;auto key=[](int x,int y){return(uint32_t(x)<<16)|y;};
 for(int i=0;i<N;i++){prev[i]=(i==0||raw[i-1]=='\n')?-1:i-1;next[i]=(i==N-1||raw[i]=='\n')?-1:i+1;sym[i]=raw[i];if(next[i]>=0){auto&b=m[key(sym[i],raw[i+1])];b.n++;b.pos.push_back(i);}}
 for(auto&kv:m){kv.second.bound=kv.second.n;q.push({kv.second.n,kv.first});}
 auto add=[&](int i){if(i<0||next[i]<0)return;uint32_t k=key(sym[i],sym[next[i]]);if(lens[sym[i]]+lens[sym[next[i]]]>maxlen)return;auto&b=m[k];b.n++;b.pos.push_back(i);if(b.n>b.bound){b.bound=std::max(b.n,b.bound*2);q.push({b.bound,k});}};
 auto sub=[&](int i){if(i<0||next[i]<0)return;uint32_t k=key(sym[i],sym[next[i]]);auto it=m.find(k);if(it!=m.end())it->second.n--;};
 for(int code=256;code<K+256;code++){uint32_t k;for(;;){if(q.empty())goto bpe_done;auto h=q.top();q.pop();auto&b=m[h.k];if(b.bound!=h.f)continue;if(h.f!=b.n){b.bound=b.n;if(b.n>1)q.push({b.n,h.k});continue;}if(b.n<2)goto bpe_done;k=h.k;break;}int a=k>>16,b=k&65535;lens[code]=lens[a]+lens[b];if(lens[code]>maxlen){m[k].n=0;code--;continue;}rule.push_back({a,b});auto positions=std::move(m[k].pos);for(int i:positions){int j=next[i];if(j<0||sym[i]!=a||sym[j]!=b)continue;int pr=prev[i],nn=next[j];sub(pr);sub(i);sub(j);sym[i]=code;next[i]=nn;if(nn>=0)prev[nn]=i;next[j]=-2;add(pr);add(i);}m[k].bound=m[k].n;if(m[k].n>1)q.push({m[k].n,k});}
 bpe_done:;
 std::vector<uint32_t>freq(rule.size()+256);for(int i=0;i<N;i++)if(next[i]!=-2)freq[sym[i]]++;std::vector<uint16_t>map;for(size_t i=0;i<freq.size();i++)if(freq[i])map.push_back(i);std::sort(map.begin(),map.end(),[&](uint16_t a,uint16_t b){return freq[a]>freq[b]||(freq[a]==freq[b]&&a<b);});std::vector<uint16_t>rev(freq.size());for(size_t i=0;i<map.size();i++)rev[map[i]]=i;
 std::vector<std::vector<uint8_t>>fr(rule.size()+256);for(int i=0;i<256;i++)fr[i].push_back(i);for(size_t i=0;i<rule.size();i++){auto&a=fr[rule[i].first];auto&b=fr[rule[i].second];fr[i+256]=a;fr[i+256].insert(fr[i+256].end(),b.begin(),b.end());}auto lexical=[&](uint16_t a,uint16_t b){return fr[a]<fr[b]||(fr[a]==fr[b]&&a<b);};std::sort(map.begin(),map.begin()+std::min(size_t(128),map.size()),lexical);if(map.size()>128)std::sort(map.begin()+128,map.end(),lexical);for(size_t i=0;i<map.size();i++)rev[map[i]]=i;std::vector<uint8_t>dict;uint32_t totalsize=0;for(auto code:map)totalsize+=fr[code].size();bpe_put(dict,totalsize);std::vector<uint8_t>previous;for(auto code:map){auto&fragment=fr[code];size_t prefix=0;while(prefix<std::min(previous.size(),fragment.size())&&previous[prefix]==fragment[prefix])prefix++;dict.push_back(prefix);dict.push_back(fragment.size()-prefix);dict.insert(dict.end(),fragment.begin()+prefix,fragment.end());previous=fragment;}std::vector<uint8_t>dc(LZ4_compressBound(dict.size()));int dcl=LZ4_compress_HC((const char*)dict.data(),(char*)dc.data(),dict.size(),dc.size(),12);if(dcl<=0)return {};dc.resize(dcl);
 std::vector<uint8_t>codes,index;size_t last=0;for(int i=0;i<N;i++)if(next[i]!=-2){uint32_t id=rev[sym[i]];if(bpe_fixedsize(size)){codes.push_back(id);codes.push_back(id>>8);}else if(id<128)codes.push_back(id);else{id-=128;codes.push_back(128+(id>>8));codes.push_back(id);}if(next[i]==-1){uint32_t len=codes.size()-last;last=codes.size();if(len<255)index.push_back(len);else{index.push_back(255);bpe_put(index,len);}}}
 std::vector<uint8_t>ic(ZSTD_compressBound(index.size()));size_t icl=ZSTD_compress(ic.data(),ic.size(),index.data(),index.size(),19);if(ZSTD_isError(icl))return {};ic.resize(icl);std::vector<uint8_t>out;bpe_put(out,0xfffffffcU);bpe_put(out,map.size());bpe_put(out,dc.size());bpe_put(out,ic.size());bpe_put(out,codes.size());bpe_put(out,dict.size());bpe_put(out,index.size());out.insert(out.end(),dc.begin(),dc.end());out.insert(out.end(),ic.begin(),ic.end());out.insert(out.end(),codes.begin(),codes.end());return out;
}
#endif
