#include <bits/stdc++.h>
using namespace std;
struct Node{int next[256];uint32_t off;Node(){memset(next,0,sizeof next);off=UINT32_MAX;}};
int main(int argc,char**argv){
 string dictfile=argc>1?argv[1]:"/work/root/dict16.bin",tokfile=argc>2?argv[2]:"/work/root/tokens16.bin",outdir=argc>3?argv[3]:"/work/grammar/compact/";
 ifstream d(dictfile,ios::binary);vector<string>dict;while(1){uint8_t len;d.read((char*)&len,1);if(!d)break;string s(len,'\0');d.read(s.data(),len);dict.push_back(s);}if(dict.empty()){cerr<<"missing dictionary\n";return 1;}
 ifstream t(tokfile,ios::binary);t.seekg(0,ios::end);size_t n=t.tellg()/2;t.seekg(0);vector<uint16_t>tok(n);t.read((char*)tok.data(),n*2);vector<size_t>cnt(dict.size());for(auto c:tok){if(c>=cnt.size()){cerr<<"bad token\n";return 1;}cnt[c]++;}
 vector<Node>trie(1);trie.reserve(500000);vector<int>nodes(dict.size());for(size_t i=0;i<dict.size();i++){int p=0;for(uint8_t c:dict[i]){if(!trie[p].next[c]){int ix=trie.size();trie.emplace_back();trie[p].next[c]=ix;}p=trie[p].next[c];}nodes[i]=p;}
 vector<int>order(dict.size());iota(order.begin(),order.end(),0);stable_sort(order.begin(),order.end(),[&](int a,int b){if(dict[a].size()!=dict[b].size())return dict[a].size()>dict[b].size();return cnt[a]>cnt[b];});vector<uint8_t>data;size_t selected=0;
 for(int id:order){if(trie[nodes[id]].off!=UINT32_MAX)continue;auto &s=dict[id];size_t overlap=min(s.size()-1,data.size());while(overlap && memcmp(data.data()+data.size()-overlap,s.data(),overlap))--overlap;size_t pos=data.size()-overlap;data.insert(data.end(),s.begin()+overlap,s.end());selected++;
 for(size_t begin=0;begin<s.size();begin++){int p=0;for(size_t end=begin;end<s.size();end++){p=trie[p].next[(uint8_t)s[end]];if(!p)break;if(trie[p].off==UINT32_MAX)trie[p].off=pos+begin;}}}
 size_t compact=data.size();data.resize((data.size()+65)&~size_t(1));stable_sort(order.begin(),order.end(),[&](int a,int b){return cnt[a]>cnt[b];});vector<uint32_t>meta(65536);vector<int>remap(dict.size());for(size_t i=0;i<dict.size();i++){int id=order[i];remap[id]=i;uint32_t off=trie[nodes[id]].off;if(off==UINT32_MAX||memcmp(data.data()+off,dict[id].data(),dict[id].size())){cerr<<"bad dictionary\n";return 1;}meta[i]=(uint32_t(dict[id].size())<<24)|off;}for(size_t i=dict.size();i<65536;i++)meta[i]=meta[0];
 ofstream payload(outdir+"payload.inc");payload<<"alignas(64) static const uint32_t meta[] = {\n";for(int i=0;i<65536;i++){payload<<meta[i]<<",";if(i%16==15)payload<<"\n";}payload<<"};\nalignas(64) static const uint8_t data[] = {\n";for(size_t i=0;i<data.size();i++){payload<<unsigned(data[i])<<",";if(i%32==31)payload<<"\n";}payload<<"};\n";
 ofstream bin(outdir+"archive.bin",ios::binary);uint64_t h[]={0x314650424d415247ULL,99999986,n,data.size()};bin.write((char*)h,sizeof h);bin.write((char*)meta.data(),meta.size()*4);bin.write((char*)data.data(),data.size());for(auto c:tok){uint16_t id=remap[c];bin.write((char*)&id,2);}cout<<"entries "<<dict.size()<<" selected "<<selected<<" compact_bytes "<<compact<<" tokens "<<n<<" archive_bytes "<<bin.tellp()<<"\n";
 // Verify the complete reconstruction and save separate binary tables for experiments.
 ifstream rf("/inputs/python-source.py",ios::binary);string raw((istreambuf_iterator<char>(rf)),{});size_t at=0;for(auto c:tok){uint32_t m=meta[remap[c]],len=m>>24;if(at+len>raw.size()||memcmp(raw.data()+at,data.data()+(m&0xffffff),len)){cerr<<"bad reconstruction at "<<at<<"\n";return 1;}at+=len;}if(at!=raw.size())return 1;ofstream mfile(outdir+"meta.bin",ios::binary);mfile.write((char*)meta.data(),meta.size()*4);ofstream datafile(outdir+"data.bin",ios::binary);datafile.write((char*)data.data(),data.size());}
