#ifndef COMPLEX_CODEC_H
#define COMPLEX_CODEC_H
#include <cstdint>
#include <immintrin.h>
#include <cstring>
#include <string>
#include <vector>
#include <algorithm>
#include <limits>
#ifdef ENCODER
#include <unordered_map>
#include <queue>
#include <cmath>
#include <stdexcept>
#endif
namespace complexcodec {
using Bytes=std::vector<uint8_t>;
inline void cp(uint8_t*d,const uint8_t*s,size_t n){while(n>64){auto v=_mm512_loadu_si512(s);_mm512_storeu_si512(d,v);s+=64;d+=64;n-=64;}__mmask64 mask=_bzhi_u64(~0ull,n);auto v=_mm512_maskz_loadu_epi8(mask,s);_mm512_mask_storeu_epi8(d,mask,v);}

inline void p32(Bytes&b,uint32_t x){for(int k=0;k<4;k++)b.push_back(uint8_t(x>>(k*8)));}
inline void p16(Bytes&b,uint32_t x){b.push_back(x);b.push_back(x>>8);}
inline uint32_t r32(const uint8_t*p){uint32_t x;memcpy(&x,p,4);return x;}
inline uint16_t r16(const uint8_t*p){uint16_t x;memcpy(&x,p,2);return x;}
struct Reader{const uint8_t*p,*end;bool ok=true;Reader(const uint8_t*a,size_t n):p(a),end(a+n){}uint32_t u32(){if(size_t(end-p)<4){ok=false;return 0;}auto x=r32(p);p+=4;return x;}uint16_t u16(){if(size_t(end-p)<2){ok=false;return 0;}auto x=r16(p);p+=2;return x;}const uint8_t* take(size_t n){if(n>size_t(end-p)){ok=false;return nullptr;}auto q=p;p+=n;return q;}};
inline uint32_t getid(const uint8_t*&p,unsigned t){unsigned c=p[0],ext=c>=t;unsigned x=c+ext*((c-t)*255+p[1]);p+=1+ext;return x;}
inline bool checkedid(Reader&r,unsigned t,uint32_t&x){if(r.end-r.p>=2){x=getid(r.p,t);return true;}if(r.p==r.end)return false;x=*r.p++;return x<t;}
inline unsigned threshold(size_t n){return std::min<size_t>(255,(65536-n)/255);}
inline bool unlz(const uint8_t*s,size_t sn,Bytes&d,size_t dn){d.resize(dn);size_t si=0,di=0;while(si<sn){unsigned t=s[si++];if(t<128){size_t n=t+1;if(n>sn-si||n>dn-di)return false;cp(d.data()+di,s+si,n);si+=n;di+=n;}else{size_t n=(t&127)+4;if(sn-si<2||n>dn-di)return false;unsigned off=r16(s+si);si+=2;if(!off||off>di)return false;if(off>=n)cp(d.data()+di,d.data()+di-off,n);else for(size_t k=0;k<n;k++)d[di+k]=d[di+k-off];di+=n;}}return di==dn;}
struct Entry{const uint8_t*p;uint32_t n;};
struct Huff {std::vector<uint32_t> tab,secondary;std::vector<uint64_t> packed,psecond;const uint8_t*data=nullptr;uint32_t bits=0,total=0,ns=0;bool complete=false;mutable size_t pos=0;mutable uint32_t num=0;
 bool open(Reader&r,unsigned maxsyms){ns=r.u32();total=r.u32();bits=r.u32();if(!r.ok||!ns||ns>maxsyms||total>10000000||bits>160000000)return false;auto lens=r.take(ns);if(!lens)return false;unsigned count[17]={},next[17]={};for(unsigned i=0;i<ns;i++){if(lens[i]>16)return false;if(lens[i])count[lens[i]]++;}unsigned code=0;for(unsigned n=1;n<=16;n++){code=(code+count[n-1])<<1;next[n]=code;if(code+count[n]>(1u<<n))return false;}complete=code+count[16]==65536;tab.assign(4096,0);secondary.clear();for(unsigned i=0;i<ns;i++){unsigned n=lens[i];if(!n)continue;unsigned c=next[n]++,rev=0;for(unsigned j=0;j<n;j++){rev=rev*2+(c&1);c>>=1;}uint32_t v=(i<<5)|n;if(n<=12){for(unsigned j=rev;j<4096;j+=1u<<n)tab[j]=v;}else{unsigned prefix=rev&4095,base;if(!tab[prefix]){base=secondary.size();tab[prefix]=0x80000000u|base;secondary.resize(base+16);}else{if(!(tab[prefix]&0x80000000u))return false;base=tab[prefix]&0x7fffffffu;}for(unsigned j=rev>>12;j<16;j+=1u<<(n-12))secondary[base+j]=v;}}data=r.take((size_t(bits)+7)/8+8);pos=0;num=0;return data!=nullptr;}
 void materialize(const std::vector<Entry>&dict,const uint8_t*base){auto cv=[&](uint32_t v)->uint64_t{if(v&0x80000000u)return (1ull<<63)|(v&0x7fffffffu);if(!(v&31))return 0;auto&e=dict[v>>5];return (uint64_t(e.p-base)<<32)|(uint64_t(e.n)<<5)|(v&31);};packed.resize(tab.size());psecond.resize(secondary.size());for(size_t i=0;i<tab.size();i++)packed[i]=cv(tab[i]);for(size_t i=0;i<secondary.size();i++)psecond[i]=cv(secondary[i]);tab.clear();tab.shrink_to_fit();secondary.clear();secondary.shrink_to_fit();}
 uint64_t nextentry()const{if(pos>=bits||num>=total)return UINT64_MAX;uint64_t w;memcpy(&w,data+(pos>>3),8);w>>=pos&7;uint64_t v=packed[w&4095];if(v>>63)v=psecond[(v&0x7fffffffu)+((w>>12)&15)];unsigned n=v&31;if(!n||pos+n>bits)return UINT64_MAX;pos+=n;num++;return v;}
 void reset()const{pos=0;num=0;}uint32_t next()const{if(pos>=bits||num>=total)return UINT32_MAX;uint64_t w;memcpy(&w,data+(pos>>3),8);w>>=pos&7;unsigned v=tab[w&4095];if(v&0x80000000u)v=secondary[(v&0x7fffffffu)+((w>>12)&15)];unsigned n=v&31;if(!n||pos+n>bits)return UINT32_MAX;pos+=n;num++;return v>>5;}bool done()const{return pos==bits&&num==total;}
};
struct Tokens {
 Bytes dictbuf;std::vector<Entry>dict;Huff counts,codes;mutable size_t next=0;size_t nr=0;
 bool open(Reader&r,size_t rowcount){nr=rowcount;uint32_t nd=r.u32(),dn=r.u32(),cn=r.u32();if(!r.ok||nd>65535||dn>20000000||cn>20000000)return false;auto z=r.take(cn);if(!z||!unlz(z,cn,dictbuf,dn))return false;Reader dr(dictbuf.data(),dictbuf.size());dict.resize(nd);for(auto&e:dict){unsigned n=dr.u16();auto p=dr.take(n);if(!p)return false;e={p,n};}if(!dr.ok||dr.p!=dr.end)return false;if(!(counts.open(r,256)&&counts.total==nr&&codes.open(r,nd)&&codes.ns==nd))return false;codes.materialize(dict,dictbuf.data());return true;}
 size_t emit(size_t row,uint8_t*out,bool attr,size_t cap)const{if(!row){counts.reset();codes.reset();next=0;}if(row!=next||cap<2)return SIZE_MAX;unsigned n=counts.next();if(n==UINT32_MAX)return SIZE_MAX;unsigned nt=n?n-1:0;size_t codepos=codes.pos;bool fast=codes.complete&&uint64_t(codes.num)+nt<=codes.total&&codepos+16*nt<=codes.bits;uint8_t*q=out;if(!n){if(cap<4)return SIZE_MAX;memcpy(q,"null",4);q+=4;}else{*q++=attr?'{':'"';cap--;for(unsigned j=1;j<n;j++){uint64_t v;if(fast){uint64_t w;memcpy(&w,codes.data+(codepos>>3),8);w>>=codepos&7;v=codes.packed[w&4095];if(v>>63)v=codes.psecond[(v&0x7fffffffu)+((w>>12)&15)];codepos+=v&31;}else{v=codes.nextentry();if(v==UINT64_MAX)return SIZE_MAX;}size_t len=(v>>5)&0x7ffffff;const uint8_t*ptr=dictbuf.data()+(v>>32);if(j+1==n){unsigned trim=attr?1:2;if(len<trim)return SIZE_MAX;len-=trim;}if(len>=cap)return SIZE_MAX;cp(q,ptr,len);q+=len;cap-=len;}*q++=attr?'}':'"';}if(fast){codes.pos=codepos;codes.num+=nt;}if(row+1==nr&&(!counts.done()||!codes.done()))return SIZE_MAX;next=row+1;return q-out;}
};

struct Hours {
 Bytes timebuf,expanded;std::vector<Entry>dict;const uint8_t*stream=nullptr,*end=nullptr;mutable const uint8_t*cursor=nullptr;mutable size_t next=0;size_t nr=0;
 bool open(Reader&r,size_t rowcount){nr=rowcount;uint32_t nt=r.u32(),tn=r.u32(),tc=r.u32();if(!r.ok||nt>65535||tn>2000000||tc>2000000)return false;auto z=r.take(tc);if(!z||!unlz(z,tc,timebuf,tn))return false;Reader tr(timebuf.data(),timebuf.size());std::vector<Entry>times(nt);for(auto&e:times){unsigned n=tr.u16();auto p=tr.take(n);if(!p)return false;e={p,n};}if(!tr.ok||tr.p!=tr.end)return false;unsigned tt=threshold(nt);uint32_t nd=r.u32(),exn=r.u32(),ncomb=r.u32();if(!r.ok||!nd||nd>65535||exn>30000000||ncomb>65535)return false;std::vector<uint16_t>comb(ncomb);for(auto&v:comb)v=r.u16();Huff masks;if(!r.ok||!masks.open(r,ncomb)||masks.ns!=ncomb||masks.total!=nd)return false;uint32_t pn=r.u32();auto ps=r.take(pn);if(!ps)return false;Reader pr(ps,pn);expanded.resize(size_t(exn)+16);dict.resize(nd);size_t pos=0;static const char*keys[]={"\"Monday\":","\"Tuesday\":","\"Wednesday\":","\"Thursday\":","\"Friday\":","\"Saturday\":","\"Sunday\":"};static const unsigned kn[]={9,10,12,11,9,11,9};
 for(auto&e:dict){uint32_t code=masks.next();if(code>=comb.size())return false;unsigned mask=comb[code]&255,ch=comb[code]>>8;size_t start=pos;if(mask==128){if(exn-pos<4)return false;memcpy(expanded.data()+pos,"null",4);pos+=4;}else{if(mask>127||pos>=exn)return false;expanded[pos++]='{';uint32_t ti=0;bool first=true;for(unsigned day=0;day<7;day++)if(mask&(1<<day)){if(first||ch&(1<<day)){if(!checkedid(pr,tt,ti)||ti>=nt)return false;}size_t need=kn[day]+times[ti].n+1;if(need>exn-pos)return false;cp(expanded.data()+pos,(const uint8_t*)keys[day],kn[day]);pos+=kn[day];cp(expanded.data()+pos,times[ti].p,times[ti].n);pos+=times[ti].n;expanded[pos++]=',';first=false;}if(!first)pos--;if(pos>=exn)return false;expanded[pos++]='}';}e={expanded.data()+start,uint32_t(pos-start)};}
 if(!pr.ok||pr.p!=pr.end||pos!=exn||!masks.done())return false;uint32_t rn=r.u32();auto rp=r.take(rn);if(!rp)return false;if(rn<nr||rn>nr*2)return false;stream=rp;end=rp+rn;cursor=stream;next=0;return true;}
 size_t emit(size_t row,uint8_t*out,size_t cap)const{if(!row){cursor=stream;next=0;}if(row!=next)return SIZE_MAX;Reader rr(cursor,end-cursor);uint32_t id;if(!checkedid(rr,threshold(dict.size()),id)||id>=dict.size())return SIZE_MAX;auto&e=dict[id];if(e.n>cap||(row+1==nr&&rr.p!=end))return SIZE_MAX;cp(out,e.p,e.n);cursor=rr.p;next=row+1;return e.n;}

};
struct State {Tokens a,c;Hours h;bool open(const uint8_t*p,size_t n,size_t rows){Reader r(p,n);return r.u32()==0x34435058&&a.open(r,rows)&&c.open(r,rows)&&h.open(r,rows)&&r.ok&&r.p==r.end;}size_t emit_attr(size_t row,uint8_t*out,size_t cap=SIZE_MAX)const{return a.emit(row,out,true,cap);}size_t emit_cat(size_t row,uint8_t*out,size_t cap=SIZE_MAX)const{return c.emit(row,out,false,cap);}size_t emit_hour(size_t row,uint8_t*out,size_t cap=SIZE_MAX)const{return h.emit(row,out,cap);}};

#ifdef ENCODER
inline void putid(Bytes&b,uint32_t x,unsigned t){if(x<t)b.push_back(x);else{x-=t;b.push_back(t+x/256);b.push_back(x%256);}}
inline Bytes lz(const Bytes&s){Bytes out;std::vector<int>tab(65536,-1),chain(s.size(),-1);size_t n=s.size(),i=0,lit=0;auto flush=[&](size_t e){while(lit<e){size_t k=std::min<size_t>(128,e-lit);out.push_back(k-1);out.insert(out.end(),s.begin()+lit,s.begin()+lit+k);lit+=k;}};while(i+4<=n){uint32_t v=r32(s.data()+i);unsigned hash=(v*2654435761u)>>16;int prev=tab[hash],bestprev=-1;chain[i]=prev;tab[hash]=i;size_t len=0;for(int steps=0;prev>=0&&i-size_t(prev)<=65535&&steps<128;steps++,prev=chain[prev]){if(r32(s.data()+prev)==v){size_t l=4;while(l<131&&i+l<n&&s[prev+l]==s[i+l])l++;if(l>len){len=l;bestprev=prev;if(l==131)break;}}}prev=bestprev;if(len>=4){flush(i);out.push_back(128+len-4);p16(out,i-prev);for(size_t j=1;j<len&&i+j+4<=n;j++){unsigned h=(r32(s.data()+i+j)*2654435761u)>>16;chain[i+j]=tab[h];tab[h]=i+j;}i+=len;lit=i;}else i++;}flush(n);return out;}
inline size_t quoted_end(const std::string&s,size_t p){if(p>=s.size()||s[p]!='"')throw std::runtime_error("complex string parse");p++;while(p<s.size()){char c=s[p++];if(c=='"')return p;if(c=='\\'){if(p==s.size())break;p++;}}throw std::runtime_error("complex unterminated string");}
inline std::vector<std::string> attrparts(const std::string&s){std::vector<std::string>out;if(s=="null"||s=="{}")return out;if(s.front()!='{'||s.back()!='}')throw std::runtime_error("complex attribute parse");size_t p=1;while(p+1<s.size()){size_t st=p;p=quoted_end(s,p);if(s[p++]!=':')throw std::runtime_error("complex attribute colon");if(s[p]=='"')p=quoted_end(s,p);else{while(p<s.size()&&s[p]!=','&&s[p]!='}')p++;}out.push_back(s.substr(st,p-st)+",");if(s[p]==',')p++;else if(s[p]=='}')break;else throw std::runtime_error("complex attribute separator");}return out;}
inline std::vector<std::string> catparts(const std::string&s){std::vector<std::string>out;if(s=="null")return out;if(s.front()!='"'||s.back()!='"')throw std::runtime_error("complex category parse");size_t p=1;while(1){size_t e=s.find(", ",p);if(e==std::string::npos){out.push_back(s.substr(p,s.size()-p-1)+", ");break;}out.push_back(s.substr(p,e-p)+", ");p=e+2;}return out;}
inline void pack_dict(Bytes&out,const std::vector<std::string>&d){Bytes raw;for(auto&s:d){if(s.size()>65535)throw std::runtime_error("complex dict length");p16(raw,s.size());raw.insert(raw.end(),s.begin(),s.end());}auto z=lz(raw);p32(out,d.size());p32(out,raw.size());p32(out,z.size());out.insert(out.end(),z.begin(),z.end());}
inline void pack_huff(Bytes&out,const std::vector<uint32_t>&seq,unsigned ns){std::vector<uint32_t>freq(ns);for(auto x:seq)freq[x]++;std::vector<unsigned>order;for(unsigned x=0;x<ns;x++)if(freq[x])order.push_back(x);std::sort(order.begin(),order.end(),[&](auto a,auto b){return freq[a]!=freq[b]?freq[a]>freq[b]:a<b;});struct Node{uint64_t f;int a,b;};std::vector<Node>nodes;using Q=std::pair<uint64_t,int>;std::priority_queue<Q,std::vector<Q>,std::greater<Q>>heap;for(auto x:order){int id=nodes.size();nodes.push_back({freq[x],-1,-1});heap.push({freq[x],id});}while(heap.size()>1){auto a=heap.top();heap.pop();auto b=heap.top();heap.pop();int id=nodes.size();nodes.push_back({a.first+b.first,a.second,b.second});heap.push({a.first+b.first,id});}unsigned counts[64]={};std::vector<std::pair<int,unsigned>>todo;if(!nodes.empty())todo.push_back({int(nodes.size()-1),0});while(!todo.empty()){auto p=todo.back();todo.pop_back();auto&n=nodes[p.first];if(n.a<0)counts[std::max(1u,p.second)]++;else{todo.push_back({n.a,p.second+1});todo.push_back({n.b,p.second+1});}}for(unsigned n=17;n<64;n++){counts[16]+=counts[n];counts[n]=0;}int64_t used=0;for(unsigned n=1;n<=16;n++)used+=int64_t(counts[n])<<(16-n);while(used>65536){unsigned b=15;while(b&&!counts[b])b--;if(!b)throw std::runtime_error("complex huff limit");counts[b]--;counts[b+1]+=2;counts[16]--;used--;}
 std::vector<uint8_t>lens(ns);size_t at=0;for(unsigned n=1;n<=16;n++)for(unsigned j=0;j<counts[n];j++)lens[order[at++]]=n;unsigned next[17]={},code=0;for(unsigned n=1;n<=16;n++){code=(code+counts[n-1])<<1;next[n]=code;}std::vector<unsigned>codes(ns);for(unsigned i=0;i<ns;i++){unsigned n=lens[i];if(!n)continue;unsigned c=next[n]++,rev=0;for(unsigned j=0;j<n;j++){rev=rev*2+(c&1);c>>=1;}codes[i]=rev;}Bytes data;uint64_t buf=0;unsigned fill=0;uint32_t bits=0;for(auto x:seq){buf|=uint64_t(codes[x])<<fill;fill+=lens[x];bits+=lens[x];while(fill>=8){data.push_back(buf);buf>>=8;fill-=8;}}if(fill)data.push_back(buf);data.resize(data.size()+8);p32(out,ns);p32(out,seq.size());p32(out,bits);out.insert(out.end(),lens.begin(),lens.end());out.insert(out.end(),data.begin(),data.end());}
inline void encode_tokens(Bytes&out,const std::vector<std::string>&input,bool attr){std::unordered_map<std::string,uint32_t>map;std::vector<std::string>d;std::vector<std::vector<uint32_t>>rows,seqs;rows.reserve(input.size());for(auto&s:input){rows.emplace_back();auto parts=attr?attrparts(s):catparts(s);for(auto&v:parts){auto it=map.emplace(v,d.size());if(it.second){d.push_back(v);seqs.push_back({uint32_t(seqs.size())});}rows.back().push_back(it.first->second);}}
 auto original=rows;const size_t maxdict=attr?4200:2200;
 for(int pass=0;pass<5&&d.size()<maxdict;pass++){std::unordered_map<uint64_t,uint32_t>cnt;for(auto&row:rows)for(size_t j=1;j<row.size();j++)cnt[(uint64_t(row[j-1])<<32)|row[j]]++;std::vector<std::pair<uint32_t,uint64_t>>best;for(auto&kv:cnt)if(kv.second>=12)best.push_back({kv.second,kv.first});std::sort(best.begin(),best.end(),[](auto&a,auto&b){return a>b;});if(best.empty())break;size_t take=std::min({best.size(),maxdict-d.size(),size_t(200)});std::unordered_map<uint64_t,uint32_t>repl;for(size_t j=0;j<take;j++){uint64_t pair=best[j].second;repl[pair]=d.size();d.push_back(d[pair>>32]+d[uint32_t(pair)]);auto seq=seqs[pair>>32];seq.insert(seq.end(),seqs[uint32_t(pair)].begin(),seqs[uint32_t(pair)].end());seqs.push_back(std::move(seq));}size_t changes=0;for(auto&row:rows){size_t w=0;for(size_t j=0;j<row.size();j++){if(j+1<row.size()){auto it=repl.find((uint64_t(row[j])<<32)|row[j+1]);if(it!=repl.end()){row[w++]=it->second;j++;changes++;continue;}}row[w++]=row[j];}row.resize(w);}if(!changes)break;}
 struct Trie{std::unordered_map<uint32_t,uint32_t>next;int id=-1;};std::vector<Trie>trie(1);for(size_t id=0;id<seqs.size();id++){unsigned node=0;for(auto x:seqs[id]){auto it=trie[node].next.find(x);if(it==trie[node].next.end()){unsigned k=trie.size();trie[node].next[x]=k;trie.emplace_back();node=k;}else node=it->second;}trie[node].id=id;}
 for(unsigned pass=0;pass<4;pass++){std::vector<uint32_t>f(d.size());uint32_t total=0;for(auto&row:rows)for(auto x:row){f[x]++;total++;}std::vector<uint32_t>cost(d.size());for(size_t x=0;x<d.size();x++)cost[x]=uint32_t(-std::log2((f[x]+0.25)/(total+0.25*d.size()))*1024)+1;for(size_t r=0;r<rows.size();r++){auto&orig=original[r];size_t n=orig.size();std::vector<uint32_t>dp(n+1,UINT32_MAX),best(n);dp[n]=0;for(size_t j=n;j-->0;){unsigned node=0;for(size_t k=j;k<n;k++){auto it=trie[node].next.find(orig[k]);if(it==trie[node].next.end())break;node=it->second;int id=trie[node].id;if(id>=0&&cost[id]+dp[k+1]<dp[j]){dp[j]=cost[id]+dp[k+1];best[j]=id;}}}rows[r].clear();for(size_t j=0;j<n;){unsigned id=best[j];rows[r].push_back(id);j+=seqs[id].size();}}}
 std::vector<uint32_t>freq(d.size());for(auto&row:rows)for(auto x:row)freq[x]++;std::vector<uint32_t>order;for(size_t j=0;j<d.size();j++)if(freq[j])order.push_back(j);std::sort(order.begin(),order.end(),[&](auto a,auto b){return freq[a]!=freq[b]?freq[a]>freq[b]:a<b;});std::vector<std::string>sd;std::vector<uint32_t>rank(d.size());for(auto x:order){rank[x]=sd.size();sd.push_back(std::move(d[x]));}pack_dict(out,sd);std::vector<uint32_t>counts,syms;for(size_t j=0;j<rows.size();j++){if(input[j]=="null")counts.push_back(0);else{if(rows[j].size()>254)throw std::runtime_error("complex row count");counts.push_back(rows[j].size()+1);for(auto x:rows[j])syms.push_back(rank[x]);}}pack_huff(out,counts,256);pack_huff(out,syms,sd.size());}

inline void encode_hours(Bytes&out,const std::vector<std::string>&input){std::unordered_map<std::string,uint32_t>rm,tm;std::vector<std::string>rd,td;std::vector<uint32_t>ri,freq;for(auto&s:input){auto it=rm.emplace(s,rd.size());if(it.second){rd.push_back(s);freq.push_back(0);}ri.push_back(it.first->second);freq[it.first->second]++;}std::vector<uint32_t>order(rd.size());for(size_t j=0;j<order.size();j++)order[j]=j;std::sort(order.begin(),order.end(),[&](auto a,auto b){return freq[a]!=freq[b]?freq[a]>freq[b]:a<b;});std::vector<uint32_t>rank(rd.size());struct Pattern{unsigned mask,change;std::vector<uint32_t>times;};std::vector<Pattern>pat;uint32_t exn=0;static const char*days[]={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};for(auto x:order){rank[x]=pat.size();auto&s=rd[x];exn+=s.size();Pattern pa{};if(s=="null")pa.mask=128;else{size_t p=1;int lastday=-1;std::string prev;while(p+1<s.size()){size_t e=quoted_end(s,p);auto key=s.substr(p+1,e-p-2);unsigned day=0;while(day<7&&key!=days[day])day++;if(day>=7||int(day)<=lastday)throw std::runtime_error("complex hour day order");lastday=day;pa.mask|=1<<day;p=e;if(s[p++]!=':')throw std::runtime_error("complex hour colon");e=quoted_end(s,p);auto val=s.substr(p,e-p);if(pa.times.empty()||val!=prev){pa.change|=1<<day;auto it=tm.emplace(val,td.size());if(it.second)td.push_back(val);pa.times.push_back(it.first->second);}prev=val;p=e;if(s[p]==',')p++;else if(s[p]=='}')break;else throw std::runtime_error("complex hour separator");}}pat.push_back(std::move(pa));}
 std::vector<uint32_t>tf(td.size());for(auto&p:pat)for(auto x:p.times)tf[x]++;std::vector<uint32_t>to(td.size()),tr(td.size());for(size_t j=0;j<to.size();j++)to[j]=j;std::sort(to.begin(),to.end(),[&](auto a,auto b){return tf[a]!=tf[b]?tf[a]>tf[b]:a<b;});std::vector<std::string>ts;for(auto x:to){tr[x]=ts.size();ts.push_back(std::move(td[x]));}pack_dict(out,ts);Bytes ps;unsigned tt=threshold(ts.size());std::unordered_map<uint32_t,uint32_t>combmap;std::vector<uint32_t>comb,masks;for(auto&p:pat){uint32_t code=p.mask|(p.change<<8);auto it=combmap.emplace(code,comb.size());if(it.second)comb.push_back(code);masks.push_back(it.first->second);for(auto x:p.times)putid(ps,tr[x],tt);}p32(out,pat.size());p32(out,exn);p32(out,comb.size());for(auto v:comb)p16(out,v);pack_huff(out,masks,comb.size());p32(out,ps.size());out.insert(out.end(),ps.begin(),ps.end());Bytes rs;unsigned rt=threshold(pat.size());for(auto x:ri)putid(rs,rank[x],rt);p32(out,rs.size());out.insert(out.end(),rs.begin(),rs.end());}
inline Bytes encode(const std::vector<std::string>&attrs,const std::vector<std::string>&cats,const std::vector<std::string>&hours){if(attrs.size()!=cats.size()||cats.size()!=hours.size())throw std::runtime_error("complex row size");Bytes out;p32(out,0x34435058);encode_tokens(out,attrs,true);encode_tokens(out,cats,false);encode_hours(out,hours);return out;}
#endif
}
#endif
