#include <bits/stdc++.h>
using namespace std;using U=uint32_t;using L=uint64_t;
double ent(vector<L>&c){double s=accumulate(c.begin(),c.end(),0.),z=0;for(auto a:c)if(a)z+=a*log2(s/a);return z/8;}
U rd(FILE*f){U x;fread(&x,4,1,f);return x;}
int main(int ac,char**av){int cap=ac>1?atoi(av[1]):4096,minm=ac>2?atoi(av[2]):3,lazy=ac>3?atoi(av[3]):1;FILE*f=fopen("/work/analysis_repair.bin","rb");U ns=rd(f),nrules=rd(f),nt=rd(f);for(int i=0;i<ns;i++){U k=rd(f);fseek(f,k,SEEK_CUR);}vector<pair<U,U>>rules(nrules);fread(rules.data(),8,nrules,f);vector<U> orig(nt);fread(orig.data(),4,nt,f);fclose(f);vector<U>d;function<void(U)>expand=[&](U x){if(x<cap)d.push_back(x);else{expand(rules[x-ns].first);expand(rules[x-ns].second);}};for(U x:orig)expand(x);int n=d.size(),N=n+1;d.push_back(0);vector<int>sa(N),r(N),nr(N),tmp(N),cnt(max(N,cap+1)),pr(N),nx(N);for(int i=0;i<n;i++)cnt[d[i]+1]++;cnt[0]++;for(int i=1;i<=cap;i++)cnt[i]+=cnt[i-1];sa[--cnt[0]]=n;for(int i=0;i<n;i++)sa[--cnt[d[i]+1]]=i;r[n]=0;int cl=1;for(int j=1;j<N;j++){if(j==1||d[sa[j]]!=d[sa[j-1]])cl++;r[sa[j]]=cl-1;}for(int h=1;h<N&&cl<N;h*=2){fill(cnt.begin(),cnt.begin()+cl,0);for(int j=0;j<N;j++){tmp[j]=sa[j]-h;if(tmp[j]<0)tmp[j]+=N;cnt[r[tmp[j]]]++;}for(int j=1;j<cl;j++)cnt[j]+=cnt[j-1];for(int j=N-1;j>=0;j--)sa[--cnt[r[tmp[j]]]]=tmp[j];nr[sa[0]]=0;int nc=1;for(int j=1;j<N;j++){int a=sa[j-1],b=sa[j];if(r[a]!=r[b]||r[(a+h)%N]!=r[(b+h)%N])nc++;nr[b]=nc-1;}r.swap(nr);cl=nc;}
vector<int>st;for(int p:sa){while(!st.empty()&&st.back()>p){nx[st.back()]=p;st.pop_back();}pr[p]=st.empty()?-1:st.back();st.push_back(p);}while(!st.empty()){nx[st.back()]=-1;st.pop_back();}
struct M{int len=0,off=0;};auto get=[&](int i){M m;for(int p:{pr[i],nx[i]})if(p>=0){int z=0,cap=n-i;while(z<cap&&d[i+z]==d[p+z])z++;if(z>m.len||(z==m.len&&i-p<m.off))m={z,i-p};}return m;};
vector<L>lc(cap),ml(n+1),ol(32),ll(n+1);uint64_t nm=0,nlit=0,lcur=0,extra=0;vector<array<int,3>>toks;for(int i=0;i<n;){M m=get(i);if(m.len>=minm&&lazy&&i+1<n){M mm=get(i+1);if(mm.len>m.len)m.len=0;}if(m.len<minm){lc[d[i]]++;nlit++;lcur++;i++;}else{ll[lcur]++;lcur=0;nm++;ml[m.len]++;int lg=31-__builtin_clz(m.off);ol[lg]++;extra+=lg;toks.push_back({i,m.len,m.off});i+=m.len;}}ll[lcur]++;cout<<"cap="<<cap<<" n="<<n<<" minm="<<minm<<" lazy="<<lazy<<" matches="<<nm<<" literals="<<nlit<<" est="<<ent(lc)+ent(ml)+ent(ol)+ent(ll)+extra/8.<<" lc="<<ent(lc)<<" ml="<<ent(ml)<<" ol="<<ent(ol)<<" ll="<<ent(ll)<<" extra="<<extra/8.<<" +rawrules="<<max(0,cap-256)*4<<"\n";
string root="/work/lzexp_tok"+to_string(cap);f=fopen((root+"_seq.bin").c_str(),"wb");fwrite(d.data(),4,n,f);fclose(f);f=fopen((root+"_matches.bin").c_str(),"wb");fwrite(toks.data(),12,toks.size(),f);fclose(f);
}
