#include <bits/stdc++.h>
using namespace std;using U=uint32_t;using L=uint64_t;
double ent(vector<L>&c){double s=accumulate(c.begin(),c.end(),0.),z=0;for(auto a:c)if(a)z+=a*log2(s/a);return z/8;}
U rd(FILE*f){U x;fread(&x,4,1,f);return x;}
int main(int ac,char**av){int cap=ac>1?atoi(av[1]):4096,minm=ac>2?atoi(av[2]):3,lazy=ac>3?atoi(av[3]):1;FILE*f=fopen("/work/analysis_repair.bin","rb");U ns=rd(f),nrules=rd(f),nt=rd(f);for(int i=0;i<ns;i++){U k=rd(f);fseek(f,k,SEEK_CUR);}vector<pair<U,U>>rules(nrules);fread(rules.data(),8,nrules,f);vector<U> orig(nt);fread(orig.data(),4,nt,f);fclose(f);vector<U>d;function<void(U)>expand=[&](U x){if(x<cap)d.push_back(x);else{expand(rules[x-ns].first);expand(rules[x-ns].second);}};for(U x:orig)expand(x);int n=d.size(),N=n+1;d.push_back(0);vector<int>sa(N),r(N),nr(N),tmp(N),cnt(max(N,cap+1)),pr(N),nx(N);for(int i=0;i<n;i++)cnt[d[i]+1]++;cnt[0]++;for(int i=1;i<=cap;i++)cnt[i]+=cnt[i-1];sa[--cnt[0]]=n;for(int i=0;i<n;i++)sa[--cnt[d[i]+1]]=i;r[n]=0;int cl=1;for(int j=1;j<N;j++){if(j==1||d[sa[j]]!=d[sa[j-1]])cl++;r[sa[j]]=cl-1;}for(int h=1;h<N&&cl<N;h*=2){fill(cnt.begin(),cnt.begin()+cl,0);for(int j=0;j<N;j++){tmp[j]=sa[j]-h;if(tmp[j]<0)tmp[j]+=N;cnt[r[tmp[j]]]++;}for(int j=1;j<cl;j++)cnt[j]+=cnt[j-1];for(int j=N-1;j>=0;j--)sa[--cnt[r[tmp[j]]]]=tmp[j];nr[sa[0]]=0;int nc=1;for(int j=1;j<N;j++){int a=sa[j-1],b=sa[j];if(r[a]!=r[b]||r[(a+h)%N]!=r[(b+h)%N])nc++;nr[b]=nc-1;}r.swap(nr);cl=nc;}
vector<int>st;for(int p:sa){while(!st.empty()&&st.back()>p){nx[st.back()]=p;st.pop_back();}pr[p]=st.empty()?-1:st.back();st.push_back(p);}while(!st.empty()){nx[st.back()]=-1;st.pop_back();}
struct M{int len=0,off=0;};auto get=[&](int i){M m;for(int p:{pr[i],nx[i]})if(p>=0){int z=0,cap=n-i;while(z<cap&&d[i+z]==d[p+z])z++;if(z>m.len||(z==m.len&&i-p<m.off))m={z,i-p};}return m;};

int depth=ac>4?atoi(av[4]):256;int rounds=ac>5?atoi(av[5]):20;int H=22;vector<int> head(1<<H,-1),prev(n,-1);auto hash=[&](int i){return ((uint64_t(d[i])<<32|d[i+1])*0x9e3779b185ebca87ULL)>>(64-H);};for(int i=0;i+1<n;i++){int h=hash(i);prev[i]=head[h];head[h]=i;}
vector<L>lc(cap,1),ml(n+1,1),ol(32,1),ll(n+1);for(int i=0;i<n;){M m=get(i);if(m.len>=3&&i+1<n&&get(i+1).len>m.len)m.len=0;if(m.len<3){lc[d[i]]++;i++;}else{ml[m.len]++;ol[31-__builtin_clz(m.off)]++;i+=m.len;}}
vector<double>dp(n+1);vector<int>choiceLen(n),choiceOff(n);float llover=2.6;
for(int round=0;round<rounds;round++){
vector<float>lcost(cap),mcost(2048),ocost(32);double suml=accumulate(lc.begin(),lc.end(),0.), summ=accumulate(ml.begin(),ml.begin()+2048,0.),sumo=accumulate(ol.begin(),ol.end(),0.);for(int i=0;i<cap;i++)lcost[i]=log2(suml/max<L>(1,lc[i]));for(int i=0;i<2048;i++)mcost[i]=log2(summ/max<L>(1,ml[i]));for(int i=0;i<32;i++)ocost[i]=log2(sumo/max<L>(1,ol[i]))+i;
for(int i=n-1;i>=0;i--){dp[i]=dp[i+1]+lcost[d[i]];choiceLen[i]=1;choiceOff[i]=0;array<pair<int,int>,1027>cand;int nc=0;auto add=[&](int p){if(p<0)return;int z=0;while(i+z<n&&d[i+z]==d[p+z])z++;if(z>=2)cand[nc++]={i-p,z};};int k=depth;if(i+1<n)for(int p=prev[i];p>=0&&k--;p=prev[p])if(d[p]==d[i]&&d[p+1]==d[i+1])add(p);add(pr[i]);add(nx[i]);sort(cand.begin(),cand.begin()+nc);int covered=1;for(int c=0;c<nc;c++){auto[off,len]=cand[c];float base=ocost[31-__builtin_clz(off)]+llover;for(int z=covered+1;z<=len;z++){double v=dp[i+z]+mcost[min(z,2047)]+base;if(v<dp[i])dp[i]=v,choiceLen[i]=z,choiceOff[i]=off;}covered=max(covered,len);}}
fill(lc.begin(),lc.end(),0);fill(ml.begin(),ml.end(),0);fill(ol.begin(),ol.end(),0);fill(ll.begin(),ll.end(),0);uint64_t nm=0,nlit=0,lcur=0,extra=0;vector<array<int,3>>toks;for(int i=0;i<n;){int len=choiceLen[i],off=choiceOff[i];if(!off){lc[d[i]]++;nlit++;lcur++;i++;}else{ll[lcur]++;lcur=0;nm++;ml[len]++;int lg=31-__builtin_clz(off);ol[lg]++;extra+=lg;toks.push_back({i,len,off});i+=len;}}ll[lcur]++;llover=ent(ll)*8/nm;cout<<"round="<<round<<" cap="<<cap<<" n="<<n<<" matches="<<nm<<" literals="<<nlit<<" est="<<ent(lc)+ent(ml)+ent(ol)+ent(ll)+extra/8.<<" lc="<<ent(lc)<<" ml="<<ent(ml)<<" ol="<<ent(ol)<<" ll="<<ent(ll)<<" extra="<<extra/8.<<" +rawrules="<<max(0,cap-256)*4<<"\n";
string root="/work/lzsearch_dp"+to_string(cap)+"_d"+to_string(depth)+"_r"+to_string(rounds);f=fopen((root+"_matches.bin").c_str(),"wb");fwrite(toks.data(),12,toks.size(),f);fclose(f);
}}
